import {
  //A {Max 6 in a row }
  AccessTime,
  AccountCircle,
  Add,
  AddCircleOutlineOutlined as AddOutline,
  AddBox,
  AddPhotoAlternate as AddImage,
  Alarm,
  AlarmOff,
  Apps as AppsIcon,
  ArrowBack,
  ArrowBackIos,
  ArrowDownward,
  ArrowDropDown,
  ArrowDropUp,
  ArrowForward,
  ArrowForwardIos,
  ArrowLeft,
  ArrowUpward,
  Assignment,
  AttachFile,
  ArchiveOutlined,
  //B
  BarChart,
  Brush,
  Build,
  //C
  Cached,
  CameraAlt as Camera,
  CalendarTodayOutlined,
  Cancel,
  CancelSharp,
  CheckCircle,
  CheckCircleOutline,
  ChatBubbleOutline as Chat,
  ChevronLeft,
  ChevronRight,
  ChromeReaderModeOutlined as Read,
  Clear,
  ClearAll,
  Close,
  CloseOutlined,
  CloudDownload,
  CloudUpload,
  CloudOutlined,
  Comment,
  Code,
  ColorLens,
  CompareArrows as CompareArrowsIcon,
  CreateNewFolder,
  Crop,
  //D
  DateRange,
  DeleteOutlined as Delete,
  DeleteTwoTone,
  Description,
  DesktopWindows,
  Devices,
  GetApp as GetAppIcon,
  DragIndicator,
  DragHandle as DragHandleIcon,
  Done,
  DoneAll,
  DoubleArrow,
  //E
  Edit,
  Equalizer,
  Error,
  Event,
  EventNote,
  EventOutlined,
  ExitToApp,
  ExpandLess,
  ExpandMore,
  Extension,
  //F
  Favorite,
  FiberManualRecordRounded as FiberManual,
  FileCopy,
  FileCopyOutlined as Copy,
  FilterList,
  GetApp,
  Folder,
  FormatListNumbered,
  FullscreenRounded,
  FullscreenExit,
  //G
  Gesture,
  //H
  Help,
  HelpOutline,
  HighlightOff,
  HighlightOffTwoTone,
  History as HistoryIcon,
  Home,
  //I
  InfoOutlined as Info,
  InsertChart as Dashboard,
  InsertDriveFile as Files,
  ImportExport,
  //k
  KeyboardArrowDown,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  KeyboardArrowUp,
  //L
  Launch,
  Link,
  List,
  LocationOn,
  LockOpen,
  //M
  Map,
  Menu as CustomMenu,
  MenuOpen,
  MeetingRoom as Meeting,
  More,
  MoreHoriz as MoreHorizontal,
  MoreVert as MoreVertical,
  MyLocation,
  MovieCreationOutlined,
  MoreVert as MoreVertIcon,
  //N
  NavigateBefore,
  NavigateNext,
  NotificationsNoneOutlined as Notification,
  NotificationsActive,
  //O
  OpenInBrowser,
  //P
  PhotoCamera,
  PhotoSizeSelectActual as Image,
  PinDrop,
  PlayArrow,
  PlaylistAdd,
  PlayCircleFilledWhite as PlayCircle,
  PollOutlined,
  PriorityHigh,
  PlayCircleOutlineOutlined as PlayCircleOutlined,
  Publish,
  //R
  RadioButtonUncheckedOutlined as RadioOutlined,
  Refresh,
  Reorder,
  ReplayTwoTone as Reset,
  RemoveCircleOutlineOutlined as RemoveOutline,
  Receipt,
  Report,
  RotateLeft as RotateLeftIcon,
  PictureAsPdf,
  //S
  Save,
  Schedule,
  Search,
  Send,
  Settings,
  ShoppingCart as Cart,
  Sort,
  SpeakerNotes as Note,
  StarBorder,
  Star as StarIcon,
  SupervisorAccount as Admin,
  Stop,
  //T
  Timer,
  TimerOff,
  Toc,
  TouchApp,
  Tune,
  //U
  UnfoldLess,
  UnfoldMore,
  Update,
  UnarchiveOutlined,
  //V
  ViewCarousel as Carousel,
  Visibility,
  VisibilityOff,
  VpnKey as Lock,
  //W
  Warning,
  Widgets,
} from "@material-ui/icons";

export const SystemIcons = {
  //A
  AccessTime,
  AccountCircle,
  Add,
  AddOutline,
  AddBox,
  AddImage,
  Admin,
  Alarm,
  AlarmOff,
  AppsIcon,
  ArrowBack,
  ArrowBackIos,
  ArrowDownward,
  ArrowDropDown,
  ArrowDropUp,
  ArrowForward,
  ArrowForwardIos,
  ArrowLeft,
  ArrowUpward,
  Assignment,
  AttachFile,
  ArchiveOutlined,
  //B
  BarChart,
  Brush,
  Build,
  //C
  Cached,
  Camera,
  CalendarTodayOutlined,
  Cancel,
  CancelSharp,
  Carousel,
  Cart,
  Chat,
  CheckCircle,
  CheckCircleOutline,
  ChevronLeft,
  ChevronRight,
  Clear,
  ClearAll,
  Close,
  CloseOutlined,
  CloudDownload,
  CloudUpload,
  CloudOutlined,
  Comment,
  Copy,
  Code,
  ColorLens,
  CompareArrowsIcon,
  CreateNewFolder,
  Crop,
  CustomMenu,
  //D
  Dashboard,
  DateRange,
  Delete,
  DeleteTwoTone,
  Description,
  DesktopWindows,
  Devices,
  GetAppIcon,
  DragIndicator,
  DragHandleIcon,
  Done,
  DoneAll,
  DoubleArrow,
  //E
  Edit,
  Equalizer,
  Error,
  Event,
  EventNote,
  EventOutlined,
  ExitToApp,
  ExpandLess,
  ExpandMore,
  Extension,

  //F
  Favorite,
  FiberManual,
  FileCopy,
  Files,
  FilterList,
  GetApp,
  Folder,
  FormatListNumbered,
  FullscreenRounded,
  FullscreenExit,
  //G
  Gesture,
  //H
  Help,
  HelpOutline,
  HighlightOff,
  HighlightOffTwoTone,
  HistoryIcon,
  Home,
  //I
  Image,
  ImportExport,
  Info,
  //k
  KeyboardArrowDown,
  KeyboardArrowLeft,
  KeyboardArrowRight,
  KeyboardArrowUp,
  //L
  Launch,
  Link,
  List,
  LocationOn,
  Lock,
  LockOpen,
  //M
  Map,
  MenuOpen,
  Meeting,
  More,
  MoreHorizontal,
  MoreVertical,
  MyLocation,
  MovieCreationOutlined,
  MoreVertIcon,
  //N
  NavigateBefore,
  NavigateNext,
  Note,
  Notification,
  NotificationsActive,
  //O
  OpenInBrowser,
  //P
  PhotoCamera,
  PinDrop,
  PlayArrow,
  PlaylistAdd,
  PlayCircle,

  PollOutlined,
  PriorityHigh,
  PlayCircleOutlined,
  PictureAsPdf,
  Publish,
  //R
  RadioOutlined,
  Read,
  Reorder,
  Reset,
  Refresh,
  RemoveOutline,
  Receipt,
  Report,
  RotateLeftIcon,
  //S
  Save,
  Schedule,
  Search,
  Send,
  Settings,
  Sort,
  Stop,
  StarBorder,
  StarIcon,
  //T
  Timer,
  Toc,
  TouchApp,
  Tune,
  TimerOff,
  //U
  UnfoldLess,
  UnfoldMore,
  Update,
  UnarchiveOutlined,
  //V
  Visibility,
  VisibilityOff,
  //W
  Warning,
  Widgets,
};
