const runtimeStyler = (props) => {
  let styles = {
    container: {
      display: "flex",
      flex: 1,
      flexDirection: "column",
      overflow: "hidden",
    },
    titlebar: {
      height: "6vh",
      backgroundColor: "rgba(245, 246, 250,0.9)",
      display: "flex",
      alignItems: "center",
      paddingLeft: 10,
    },
    subContainer: {
      display: "flex",
      flexDirection: "row",
      backgroundColor: "#ffffff",
    },
    calendarContainer: {
      height: "91vh",
      scrollbarWidth: "none",
      dispay: "flex",
      flex: 1,
      margin: 10,
      overflow: "hidden",
    },
    contextContainer: {
      overflow: "hidden",
      backgroundColor: "#ffffff",
      borderRadius: 5,
      display: "flex",
      flexGrow: 0.2,
      flexDirection: "column",
      maxWidth: 450,
      maxHeight: "91vh",
      margin: 5,
    },
    contextHeader: {
      backgroundColor: "#ffffff",
      borderBottom: "0.5px solid #fafafa",
      borderTopLeftRadius: 5,
      borderTopRightRadius: 5,
      maxHeight: 50,
      flex: 1,
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      paddingLeft: 10,
      paddingRight: 10,
    },
    contextSection: {
      marginLeft: 10,
      marginTop: 10,
      maxHeight: 40,
      flex: 1,
      display: "flex",
    },
    cardContainer: {
      display: "flex",
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 5,
      borderRadius: 5,
      padding: 5,
    },
    popupContainer: {
      flex: 1,
      display: "flex",
      flexDirection: "column",
      maxHeight: 300,
      width: 350,
      overflowX: "hidden",
    },
    listContainer: { width: "100%", maxWidth: 360, backgroundColor: "#fff" },
    //calendarDetails
    detailToolBar: { display: "flex", justifyContent: "space-between" },
    detailContainer: {
      display: "flex",
      flexDirection: "row",
      margin: 10,
      maxHeight: "90vh",
      overflow: "hidden",
    },
    entityAContainer: {
      flex: 1,
      marginLeft: 10,
      display: "flex",
      height: "90vh",
      alignSelf: "flex-start",
      flexDirection: "column",
    },
    entityBContainer: {
      display: "flex",
      height: "90vh",
      alignSelf: "flex-start",
      flexDirection: "column",
      overflow: "hidden",
      marginLeft: 10,
      marginRight: 10,
    },
    eventSelector: {
      display: "flex",
      width: 300,
      flexDirection: "column",
      backgroundColor: "#fafafa",
      padding: 10,
    },
  };
  return styles;
};

export default runtimeStyler;
