export const style = {
  main: {
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    flex: 1,
  },
  header: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    margin: 10,
    overflow: "hidden",
  },
  container: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    marginRight: 5,
    overflow: "auto",
  },
  actionCardContainer: {
    display: "flex",
    margin: 5,
    backgroundColor: "#cccccc",
    flexDirection: "column",
    borderRadius: 2,
    overflowX: "hidden",
    flexWrap: "wrap",
  },
  descriptionContainer: {
    display: "flex",
    flex: 8,
    flexWrap: "wrap",
    // display: 'inline-block',
    flexDirection: "column",
    wordBreak: "break-all",
    margin: 10,
  },
  descriptionBody: {
    display: "flex",
    flexWrap: "wrap",
    flexDirection: "column",
    lineHeight: 1.5,
    letterSpacing: 0,
    fontSize: 14,
  },
  cardFooter: {
    display: "flex",
    flex: 2,
    flexDirection: "column",
    padding: 10,
    backgroundColor: "#ffffff",
  },
  footerContent: {
    display: "flex",
    margin: 2,
    alignItems: "center",
    fontSize: 12,
  },
  footerTitle: {
    paddingBottom: 2,
    display: "flex",
    margin: 2,
    alignItems: "center",
    fontSize: 16,
    fontFamily: "inherit",
    fontWeight: 400,
  },
};
