export default [
  {
    name: "requestInfo",
    title: "Request Info",
    type: "SECTION",
    marker: "start",
    visible: false,
    canUpdate: true,
  },
  {
    name: "workOrderData",
    title: "Work Order Data",
    type: "SUBSECTION",
    canUpdate: true,
  },
  {
    name: "archive",
    title: "Archive",
    type: "LIST",
    placeHolder: "Select Archive",
    visible: false,
    defaultValue: "UnArchive",
    hideOnDetail: true,
    values: [
      {
        id: "Archive",
        value: "Archive",
      },
      {
        id: "UnArchive",
        value: "UnArchive",
      },
    ],
    canUpdate: true,
    audit: true,
  },
  {
    name: "workOrderNumber",
    title: "W/O Number",
    type: "SEQUENCE",
    prefix: "WO-",
    initialCount: "00001",
    "visible_summa ry": true,
    visible: true,
    order: 1,
    step: 1,
    audit: true,
    canUpdate: true,
  },
  {
    name: "workOrderTitle",
    title: "Title",
    type: "TEXTBOX",
    placeHolder: "Enter Title",
    visible: true,
    order: 2,
    colSpan: 3,
    columnWidth: 150,
    disable: false,
    displayOnCsv: true,
    bulkOperation: true,
    visibleOn360: true,
    required: true,
    info: "Enter Title",
    canUpdate: true,
    audit: true,
  },
  {
    name: "priority",
    title: "Priority",
    type: "LIST",
    placeHolder: "select any one option from the list",
    validationRegEx: "",
    info: "select any one option from the list",
    required: false,
    visible: true,
    order: 5,
    bulkOperation: true,
    showOnDetailHeader: true,
    disable: false,
    showNone: false,
    values: [
      {
        id: "High",
        value: "High",
        color: "#D32D41",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/high.svg",
      },
      {
        id: "Medium",
        value: "Medium",
        color: "#996600",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/medium.svg",
      },
      {
        id: "Low",
        value: "Low",
        color: "#6AB187",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/low.svg",
      },
    ],
    multiSelect: false,
    canUpdate: true,
    audit: true,
  },
  {
    name: "requestor",
    title: "Requestor",
    type: "REFERENCE",
    uiGridDisplayFieldName: "uiGridDisplayString",
    info: "Select the Requestor",
    validationRegEx: "",
    visibleOn360: true,
    multiSelect: false,
    required: true,
    showOnDetailHeader: true,
    visible: true,
    order: 7,
    visibleInSingleColumn: true,
    placeHolder: "Select the Requestor",
    static_filters: [
      {
        name: "roleName.name",
        value: "Shop Supervisor,Fleet Manager,Administrator",
      },
    ],
    displayFields: [
      {
        name: "firstName",
        friendlyName: "First Name",
        uiGridDisplay: true,
        delimiter: " ",
      },
      {
        name: "lastName",
        friendlyName: "Last Name",
        uiGridDisplay: true,
      },
      {
        name: "roleName.name",
        friendlyName: "Role Name",
        uiGridDisplay: true,
        visible: false,
      },
      {
        name: "email",
        friendlyName: "Email",
        uiGridDisplay: true,
        visible: false,
      },
    ],
    delimiter: " ",
    displayOnCsv: true,
    appName: "NueGov",
    audit: true,
    moduleName: "Admin",
    entityName: "User",
    canUpdate: true,
  },
  {
    name: "authorizingShopSupervisor",
    title: "Authorizing Shop Supervisor",
    type: "REFERENCE",
    uiGridDisplayFieldName: "uiGridDisplayString",
    info: "Select the Requestor",
    validationRegEx: "",
    visibleOn360: true,
    multiSelect: false,
    required: false,
    visible: false,
    visibleInSingleColumn: true,
    placeHolder: "Select Supervisor",
    static_filters: [
      {
        name: "roleName.name",
        value: "Shop Supervisor",
      },
    ],
    displayFields: [
      {
        name: "firstName",
        friendlyName: "First Name",
        uiGridDisplay: true,
        delimiter: " ",
      },
      {
        name: "lastName",
        friendlyName: "Last Name",
        uiGridDisplay: true,
      },
      {
        name: "roleName.name",
        friendlyName: "Role Name",
        uiGridDisplay: true,
        visible: false,
      },
      {
        name: "email",
        friendlyName: "Email",
        uiGridDisplay: true,
        visible: false,
      },
    ],
    delimiter: " ",
    displayOnCsv: true,
    appName: "NueGov",
    audit: true,
    moduleName: "Admin",
    entityName: "User",
    canUpdate: true,
  },
  {
    name: "issueCategory",
    title: "Category",
    required: false,
    type: "LIST",
    hideOnDetail: false,
    order: 3,
    multiSelect: true,
    placeHolder: "Select Issue Category",
    values: [
      {
        value: "Braking System",
        id: "Braking System",
      },
      {
        value: "Chassis and Body",
        id: "Chassis and Body",
      },
      {
        value: "Couplings, Plumbing and Belts",
        id: "Couplings, Plumbing and Belts",
      },
      {
        value: "Drivability and Safety Checks",
        id: "Drivability and Safety Checks",
      },
      {
        value: "Engine Breakdown",
        id: "Engine Breakdown",
      },
      {
        value: "Electrical Systems",
        id: "Electrical Systems",
      },
      {
        value: "Engine, Transmission and Exhaust",
        id: "Engine, Transmission and Exhaust",
      },
      {
        value: "General Service",
        id: "General Service",
      },
      {
        value: "Oil Change & Fluid Inspection",
        id: "Oil Change & Fluid Inspection",
      },
      {
        value: "Wheels, Tires & Brakes Inspection",
        id: "Wheels, Tires & Brakes Inspection",
      },
      {
        value: "Others",
        id: "Others",
      },
    ],
    visible: false,
    displayOnCsv: true,
    canUpdate: true,
    audit: true,
  },
  {
    name: "descriptionOfProblem",
    title: "Problem Description",
    type: "TEXTAREA",
    rows: "4",
    widthRatio: "7",
    placeHolder: "Describe problem here",
    info: "Describe the Problem",
    validationRegEx: "",
    visible: false,
    required: false,
    audit: true,
    canUpdate: true,
  },
  {
    name: "vehicleOrGear",
    title: "Asset",
    type: "SUBSECTION",
    canUpdate: true,
  },
  {
    name: "typeOf",
    title: "Asset Type",
    type: "LIST",
    placeHolder: "Select Vehicle or Gear",
    validationRegEx: "",
    required: true,
    visible: true,
    disableCellEdit: true,
    order: 3,
    values: [
      {
        value: "FEPP Engine",
        id: "FEPP Engine",
      },
      {
        value: "Fire Fleet Vehicle",
        id: "Fire Fleet Vehicle",
      },
      {
        value: "Radio",
        id: "Radio",
      },
      {
        value: "Snowmobile",
        id: "Snowmobile",
      },
      {
        value: "UTV",
        id: "UTV",
      },
      {
        value: "Vehicle",
        id: "Vehicle",
      },
    ],
    canUpdate: true,
    audit: true,
  },
  {
    name: "asset",
    title: "FEPP Engine",
    type: "REFERENCE",
    appName: "NueGov",
    required: false,
    multiReference: false,
    hideAssignment: true,
    visibleInSingleColumn: true,
    displayFields: [
      {
        name: "engineMakeModel",
        friendlyName: "Make/Model",
        visible: true,
        type: "DATAPAIREDLIST",
        delimiter: " ",
        visibleInSingleColumn: true,
      },
    ],
    delimiter: "",
    visible: true,
    order: 4,
    displayOnCsv: true,
    multiSelect: false,
    canUpdate: true,
    bulkOperation: true,
    audit: true,
    moduleName: "FPCS Fleet",
    entityName: "FeppEngine",
    showOn: {
      listenTo: "typeOf",
      values: ["FEPP Engine"],
    },
  },
  {
    name: "asset",
    title: "Fire Fleet Vehicle",
    type: "REFERENCE",
    appName: "NueGov",
    validationRegEx: "",
    required: false,
    hideAssignment: true,
    multiReference: false,
    visibleInSingleColumn: true,
    displayFields: [
      {
        name: "vehicleMakeModel",
        friendlyName: "Make/Model",
        visible: true,
        type: "DATAPAIREDLIST",
        visibleInSingleColumn: true,
      },
      {
        name: "vin",
        friendlyName: "Fire FLeet Vehicle VIN",
        uiGridDisplay: true,
        visibleInSingleColumn: true,
      },
    ],
    delimiter: "",
    visible: true,
    order: 4,
    displayOnCsv: true,
    multiSelect: false,
    canUpdate: true,
    bulkOperation: true,
    audit: true,
    moduleName: "FPCS Fleet",
    entityName: "WfmsVehicle",
    showOn: {
      listenTo: "typeOf",
      values: ["Fire Fleet Vehicle"],
    },
  },
  {
    name: "asset",
    title: "Vehicle",
    type: "REFERENCE",
    appName: "NueGov",
    validationRegEx: "",
    required: false,
    hideAssignment: true,
    multiReference: false,
    displayFields: [
      {
        name: "vehicleMakeModel",
        friendlyName: "Make/Model",
        type: "DATAPAIREDLIST",
        visible: true,
        visibleInSingleColumn: true,
      },
      {
        name: "vinNumber",
        friendlyName: "Vehicle VIN",
        uiGridDisplay: true,
        visible: false,
      },
    ],
    delimiter: "",
    visible: true,
    order: 4,
    displayOnCsv: true,
    multiSelect: false,
    canUpdate: true,
    bulkOperation: true,
    audit: true,
    moduleName: "StandardFleet",
    entityName: "Vehicle",
    showOn: {
      listenTo: "typeOf",
      values: ["Vehicle"],
    },
  },
  {
    name: "asset",
    title: "UTV",
    type: "REFERENCE",
    placeHolder: "Select UTV",
    visible: true,
    order: 4,
    displayOnCsv: true,
    hideAssignment: true,
    required: false,
    visibleOn360: true,
    width: 1500,
    info: "Select UTV",
    column: "Name",
    displayFields: [
      {
        name: "utvMakeModel",
        friendlyName: "Make/Model",
        type: "PAIREDLIST",
        visible: true,
        visibleInSingleColumn: true,
      },
      {
        name: "vin",
        friendlyName: "UTV VIN",
        uiGridDisplay: true,
      },
    ],
    appName: "NueGov",
    canUpdate: true,
    audit: true,
    bulkOperation: false,
    moduleName: "FPCS Fleet",
    entityName: "Utv",
    showOn: {
      listenTo: "typeOf",
      values: ["UTV"],
    },
  },
  {
    name: "asset",
    title: "Radio",
    type: "REFERENCE",
    placeHolder: "Select Radio",
    visible: true,
    order: 4,
    displayOnCsv: true,
    required: false,
    hideAssignment: true,
    visibleOn360: true,
    width: 1500,
    info: "Select Radio",
    column: "Name",
    displayFields: [
      {
        name: "make",
        friendlyName: "Make",
        visible: true,
        visibleInSingleColumn: true,
      },
      {
        name: "model",
        friendlyName: "Model",
        visible: true,
        visibleInSingleColumn: true,
      },
    ],
    appName: "NueGov",
    canUpdate: true,
    audit: true,
    bulkOperation: false,
    moduleName: "FPCS Fleet",
    entityName: "Radio",
    showOn: {
      listenTo: "typeOf",
      values: ["Radio"],
    },
  },
  {
    name: "odometerIn",
    title: "ODOMETER IN",
    type: "TEXTBOX",
    placeHolder: "Enter Reading",
    visible: false,
    colSpan: 3,
    columnWidth: 150,
    disable: false,
    displayOnCsv: true,
    bulkOperation: true,
    visibleOn360: true,
    required: false,
    info: "Enter Reading",
    canUpdate: true,
    audit: true,
  },
  {
    name: "odometerOut",
    title: "ODOMETER OUT",
    type: "TEXTBOX",
    placeHolder: "Enter Reading",
    visible: false,
    colSpan: 3,
    columnWidth: 150,
    disable: false,
    displayOnCsv: true,
    bulkOperation: true,
    visibleOn360: true,
    required: false,
    info: "Enter Reading",
    canUpdate: true,
    audit: true,
  },
  {
    name: "doYouNeedLoaner",
    title: "Do You Need Loaner ?",
    type: "RADIO",
    required: false,
    visibleOnCsv: false,
    values: [
      {
        value: true,
        title: "Yes",
        color: "#ee5253",
      },
      {
        value: false,
        title: "No",
        color: "#10ac84",
      },
    ],
    visible: false,
    disable: false,
    info: "",
    canUpdate: true,
    audit: true,
  },
  {
    name: "doesTheVehicleNeedToBeTowed",
    title: "Does The Vehicle Need To Be Towed ?",
    type: "RADIO",
    required: false,
    visibleOnCsv: false,
    values: [
      {
        value: true,
        title: "Yes",
        color: "#ee5253",
      },
      {
        value: false,
        title: "No",
        color: "#10ac84",
      },
    ],
    visible: false,
    disable: false,
    info: "",
    canUpdate: true,
    audit: true,
  },
  {
    name: "mechanic",
    title: "Assign Mechanic(s)",
    type: "REFERENCE",
    uiGridDisplayFieldName: "uiGridDisplayString",
    info: "Select the Mechanic",
    validationRegEx: "",
    description: "Search and Select to Assign Mechanic(s)",
    visibleInSingleColumn: true,
    visibleOn360: true,
    multiSelect: true,
    required: false,
    visible: true,
    order: 8,
    placeHolder: "Select the Mechanic",
    column: "name, phoneNumber",
    static_filters: [
      {
        name: "roleName.name",
        value: "Mechanic",
      },
    ],
    displayFields: [
      {
        name: "firstName",
        friendlyName: "First Name",
        uiGridDisplay: true,
        delimiter: " ",
      },
      {
        name: "lastName",
        friendlyName: "Last Name",
        uiGridDisplay: true,
      },
    ],
    delimiter: " ",
    displayOnCsv: true,
    appName: "NueGov",
    audit: true,
    moduleName: "Admin",
    entityName: "User",
    canUpdate: true,
  },
  {
    name: "workOrderLifecycle",
    title: "W/O Status & Key Dates",
    type: "SUBSECTION",
    canUpdate: true,
  },
  {
    name: "workOrderStatus",
    title: "W/O Status ",
    type: "LIST",
    placeHolder: "select any one option from the list",
    validationRegEx: "",
    info: "select any one option from the list img",
    required: false,
    visible: true,
    order: 5,
    enableCellEdit: true,
    showOnDetailHeader: true,
    showNone: false,
    bulkOperation: true,
    disable: false,
    defaultValue: "Open",
    values: [
      {
        id: "Open",
        value: "Open",
        color: "#EA8D00",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/open.svg",
      },
      {
        id: "In-Progress",
        value: "In-Progress",
        color: "#AF65FA",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/inprogress.svg",
      },
      {
        id: "Completed",
        value: "Completed",
        color: "#4BA86E",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/completed.svg",
      },
      {
        id: "On Hold",
        value: "On Hold",
        color: "#EA8D00",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/open.svg",
      },
    ],
    multiSelect: false,
    canUpdate: true,
    audit: true,
  },
  {
    name: "receivedDate",
    title: "Received Date",
    type: "DATE",
    format: "MM-dd-yyyy",
    mobileFormat: "MM-DD-YYYY",
    placeHolder: "MM-dd-yyyy",
    columnWidth: 150,
    info: "Select Received Date",
    validationRegEx: "",
    visibleOnCsv: true,
    displayOnCsv: true,
    colSpan: 3,
    visibleOn360: true,
    required: false,
    visible: true,
    order: 9,
    defaultValue: false,
    canUpdate: true,
    audit: true,
  },
  {
    name: "estimatedCompletedDate",
    title: "Estimated Completion Date",
    type: "DATE",
    format: "MM-dd-yyyy",
    mobileFormat: "MM-DD-YYYY",
    placeHolder: "MM-dd-yyyy",
    columnWidth: 150,
    info: "Select Estimated Completed Date",
    validationRegEx: "",
    visibleOnCsv: true,
    displayOnCsv: true,
    colSpan: 3,
    visibleOn360: true,
    required: false,
    visible: true,
    order: 10,
    defaultValue: false,
    canUpdate: true,
    audit: true,
  },
  {
    name: "workCompletedDate",
    title: "Actual Completion Date",
    type: "DATE",
    format: "MM-dd-yyyy",
    mobileFormat: "MM-DD-YYYY",
    placeHolder: "MM-dd-yyyy",
    columnWidth: 150,
    info: "Select Work Completed Date",
    validationRegEx: "",
    colSpan: 3,
    visibleOn360: true,
    required: false,
    visible: true,
    order: 11,
    canUpdate: true,
    audit: true,
  },
  {
    name: "readyDate",
    title: "Pickup/Delivery Date",
    type: "DATE",
    format: "MM-dd-yyyy",
    mobileFormat: "MM-DD-YYYY",
    placeHolder: "MM-dd-yyyy",
    columnWidth: 150,
    info: "Select Ready Date",
    validationRegEx: "",
    visibleOnCsv: true,
    displayOnCsv: true,
    colSpan: 3,
    visibleOn360: true,
    required: false,
    visible: true,
    order: 12,
    defaultValue: false,
    canUpdate: true,
    audit: true,
  },
  {
    name: "reasonForDelay",
    title: "Reason For Delay",
    type: "TEXTAREA",
    rows: "4",
    widthRatio: "3",
    placeHolder: "Enter the reason for delay",
    info: "Enter the reason for dealy",
    validationRegEx: "",
    visible: false,
    required: false,
    audit: true,
    canUpdate: true,
  },
  {
    name: "ietAndResolutionData",
    title: "IET and Resolution Data",
    type: "SUBSECTION",
    canUpdate: true,
  },
  {
    name: "iet#Number1",
    title: "IET Number 1",
    type: "TEXTBOX",
    placeHolder: "Enter Number",
    visible: false,
    validationRegEx: "",
    colSpan: 3,
    columnWidth: 150,
    disable: false,
    displayOnCsv: true,
    bulkOperation: true,
    visibleOn360: true,
    required: false,
    info: "Enter Number",
    canUpdate: true,
    audit: true,
  },
  {
    name: "iet#Number2",
    title: "IET Number 2",
    type: "TEXTBOX",
    placeHolder: "Enter Number",
    visible: false,
    validationRegEx: "",
    colSpan: 3,
    columnWidth: 150,
    disable: false,
    displayOnCsv: true,
    bulkOperation: true,
    visibleOn360: true,
    required: false,
    info: "Enter Number",
    canUpdate: true,
    audit: true,
  },
  {
    name: "ietStatus",
    title: "IET Status ",
    type: "LIST",
    placeHolder: "select any one option from the list",
    validationRegEx: "",
    info: "select any one option from the list img",
    required: false,
    visible: false,
    enableCellEdit: true,
    showNone: false,
    bulkOperation: true,
    disable: false,
    defaultValue: "Open",
    values: [
      {
        id: "Open",
        value: "Open",
        color: "#EA8D00",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/open.svg",
      },
      {
        id: "In-Progress",
        value: "In-Progress",
        color: "#AF65FA",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/inprogress.svg",
      },
      {
        id: "Completed",
        value: "Completed",
        color: "#4BA86E",
        icon: "https://assetgov-icons.s3.us-west-2.amazonaws.com/reacticons/completed.svg",
      },
    ],
    multiSelect: false,
    canUpdate: true,
    audit: true,
  },
  {
    name: "requestInfo",
    title: "Request Info",
    type: "SECTION",
    marker: "end",
    visible: false,
    canUpdate: true,
  },
  {
    name: "lineItems",
    title: "Line Items",
    type: "SECTION",
    marker: "start",
    visible: false,
    canUpdate: true,
  },
  {
    name: "lineItemInfo",
    title: "Line Item Info",
    type: "TEXTAREA",
    rows: "4",
    widthRatio: "3",
    placeHolder: "Description Of Line Item",
    info: "Description Of Line Item",
    validationRegEx: "",
    visible: false,
    required: false,
    audit: true,
    hideOnDetail: true,
    canUpdate: true,
  },
  {
    name: "lineItemType",
    title: "Line Item Type",
    type: "REFERENCE",
    uiGridDisplayFieldName: "uiGridDisplayString",
    info: "Select the Part",
    validationRegEx: "",
    visibleOn360: true,
    multiSelect: true,
    required: false,
    hideOnDetail: true,
    showOnDetailHeader: false,
    visible: false,
    visibleInSingleColumn: true,
    placeHolder: "Select the Part",
    displayFields: [
      {
        name: "lineItemType",
        friendlyName: "Line Item Type",
        uiGridDisplay: true,
        delimiter: " ",
      },
    ],
    delimiter: " ",
    displayOnCsv: true,
    appName: "NueGov",
    audit: true,
    moduleName: "WorkOrderManagement",
    entityName: "lineItems",
    canUpdate: true,
  },
  {
    name: "partsDetails",
    title: "Part Details",
    type: "REFERENCE",
    uiGridDisplayFieldName: "uiGridDisplayString",
    info: "Select the Part",
    validationRegEx: "",
    visibleOn360: true,
    multiSelect: false,
    required: false,
    hideOnDetail: true,
    showOnDetailHeader: false,
    visible: false,
    visibleInSingleColumn: true,
    placeHolder: "Select the Part",
    displayFields: [
      {
        name: "partNumber",
        friendlyName: "Part Number",
        uiGridDisplay: true,
        delimiter: " ",
      },
      {
        name: "partName",
        friendlyName: "Part Name",
        uiGridDisplay: true,
      },
      {
        name: "category",
        friendlyName: "Category",
        uiGridDisplay: true,
        visible: false,
      },
      {
        name: "invoiceNumber",
        friendlyName: "Invoice Number",
        uiGridDisplay: true,
        visible: false,
      },
      {
        name: "purchasePricePerUnit",
        friendlyName: "Purchase Price Per Unit",
        uiGridDisplay: true,
        visible: false,
      },
      {
        name: "quantityPurchased",
        friendlyName: "Quantity Purchased",
        uiGridDisplay: true,
        visible: false,
      },
      {
        name: "currentQuantity",
        friendlyName: "Current Quantity",
        uiGridDisplay: true,
        visible: false,
      },
    ],
    delimiter: " ",
    displayOnCsv: true,
    appName: "NueGov",
    audit: true,
    moduleName: "WorkOrderManagement",
    entityName: "parts",
  },
  {
    name: "partLineItems",
    type: "LINEITEM",
    title: "Part Line Item",
  },
  {
    name: "lineItems",
    title: "Line Items",
    type: "SECTION",
    marker: "end",
    visible: false,
    canUpdate: true,
  },
  {
    name: "documents",
    title: "Documents/Pictures",
    type: "SECTION",
    marker: "start",
    visible: false,
    canUpdate: true,
  },
  {
    name: "documents",
    title: "Documents",
    nameTitle: "documentName",
    descriptionTitle: "description",
    type: "DOCUMENT",
    validationRegEx: "",
    required: false,
    info: "Attach Picture",
    visible: false,
    displayOnCsv: true,
    displayOnReports: false,
    visibleOnCard: true,
    File_Limits: 3072,
    canUpdate: true,
    audit: true,
  },
  {
    name: "pictures",
    title: "Pictures",
    nameTitle: "documentName",
    descriptionTitle: "description",
    type: "CAMERA",
    validationRegEx: "",
    required: false,
    info: "Attach Picture",
    visible: false,
    displayOnCsv: true,
    visibleOnCard: true,
    displayOnReports: false,
    File_Limits: 3072,
    canUpdate: true,
    audit: true,
  },
  {
    name: "documents",
    title: "Documents/Pictures",
    type: "SECTION",
    marker: "end",
    visible: false,
    canUpdate: true,
  },
];
